### ISSUE TITLE
Add support for 3rd party beneficiaries (collection partnerships)

### ISSUE THREAD

**Issue by elmariachi111** [SpliceNFT/splicenft#170]
The Splice protocol should be able to split platform fees with another selected beneficiary.

The style owner's minting share shouldn't be affected: they receive 85% of all fees. The remaining 15% *can* be further broken down.

Assuming we're partnering with an NFT collection. Upon style minting we're signalling that splice mints of that style are restricted to that collection's hodlers (now known as "collection constraint"). The partner will provide a beneficiary address that receives the split free. Upon a mint, the the beneficiary account receives 50% of the platform share ( = 7.5% )

Assume that even though we're partnering with a collection no one feels like minting. Partnerships are therefore timeboxed: x days after the style mint arbitrary NFT holders will be eligible to mint for their NFTs and the 3rd party beneficiary split becomes obsolete.

It should still be possible to restrict a style to mint only from certain origins, regardless of that origin collection being an active "partner" (because certain styles might be aesthetically related to a certain collection)

**Comment by SuperLlama9** [comment]
Splice enables collections to create new derivatives for their community. In collaboration, we enable a specific collection, the exclusive time-based mint opportunity, of a future Splice drop. After a - to be defined - timespan, the Splice drop is available for all other collections to mint. Furthermore, the collaborating collection can name a beneficiary (i.e. the collection treasury) that receives XX% fees from all mints, bringing more power and opportunities to their community.
